--Query most important attributes of the FCW event intervals

--$fullmeas
--!FULLMEAS
--$measurement
--!MEAS
--$start [s]
--!STARTTIME
--$duration [s]
--!DURATION
--$moving state
--!LABEL "moving state"
--$asso state
--!LABEL "asso state"
--$cascade phase
--!LABEL "AEBS cascade phase"
--$event
--!LABEL "AEBS resim phase"
--$ego speed [km/h]
--!QUANTITY "ego vehicle", "speed start", 3.6
--$total mileage [km]
--!QUANTITY "ego vehicle", "mileage"
--$event start time diff
--!QUANTITY "ego vehicle", "event start time diff"
--$dx [m]
--!QUANTITY "target", "dx start"
--$vx [km/h]
--!QUANTITY "target", "vx start", 3.6
--$ax [m/s^2]
--!QUANTITY "target", "ax start"
--$measurement warning rating scale
--!LABEL "event severity"
--$resimulation warning rating scale
--!LABEL "resim event severity"
--$resim useCaseMode warning rating scale
--!LABEL "resim useCaseMode severity"
--$warning cause
--!LABEL "AEBS event cause"
--$event road type
--!LABEL "road type"
--$event source
--!LABEL "Delta report data"
--$comment
--!COMMENT
