--Query most important attributes of the AEBS event intervals

--$fullmeas
--!FULLMEAS
--$measurement
--!MEAS
--$start [s]
--!STARTTIME
--$duration [s]
--!DURATION
--$Event
--!LABEL "TSR verdict"
--$WeatherCondition
--!LABEL "Weather Conditions"
--$TimeCondition
--!LABEL "Time"
--$TSRRemark
--!LABEL "TSR Remark"
--$CAN_Signal_group
--!LABEL 'CAN_Signal_group'
--$Sign class ID
--!QUANTITY 'TSR', 'sign_class_id'
--$CAN Sign class ID
--!QUANTITY 'TSR', 'CAN_sign_class_id'
--$TSR_SpeedLimit1_E8_sE8
--!QUANTITY 'TSR', 'TSR_SpeedLimit1_E8_sE8'
--$TSR_SpeedLimit1Supplementary_E8_sE8
--!QUANTITY 'TSR', 'TSR_SpeedLimit1Supplementary_E8_sE8'
--$TSR_SpeedLimit2_E8_sE8
--!QUANTITY 'TSR', 'TSR_SpeedLimit2_E8_sE8'
--$TSR_SpeedLimitElectronic_E8_sE8
--!QUANTITY 'TSR', 'TSR_SpeedLimitElectronic_E8_sE8'
--$TSR_NoPassingRestriction_E8_sE8
--!QUANTITY 'TSR', 'TSR_NoPassingRestriction_E8_sE8'
--$TSR_CountryCode_E8_sE8
--!QUANTITY 'TSR', 'TSR_CountryCode_E8_sE8'
--$AutoHighLowBeamControl
--!QUANTITY 'TSR', 'AutoHighLowBeamControl'
--$TSSCurrentRegion
--!QUANTITY 'TSR', 'TSSCurrentRegion'
--$TSSDetectedStatus
--!QUANTITY 'TSR', 'TSSDetectedStatus'
--$TSSDetectedUoM
--!QUANTITY 'TSR', 'TSSDetectedUoM'
--$TSSDetectedValue
--!QUANTITY 'TSR', 'TSSDetectedValue'
--$TSSLifeTime
--!QUANTITY 'TSR', 'TSSLifeTime'
--$TSSOverspeedAlert
--!QUANTITY 'TSR', 'TSSOverspeedAlert'
--$CAN_AutoHighLowBeamControl
--!QUANTITY 'TSR', 'CAN_AutoHighLowBeamControl'
--$CAN_TSSCurrentRegion
--!QUANTITY 'TSR', 'CAN_TSSCurrentRegion'
--$CAN_TSSDetectedStatus
--!QUANTITY 'TSR', 'CAN_TSSDetectedStatus'
--$CAN_TSSDetectedUoM
--!QUANTITY 'TSR', 'CAN_TSSDetectedUoM'
--$CAN_TSSDetectedValue
--!QUANTITY 'TSR', 'CAN_TSSDetectedValue'
--$CAN_TSSLifeTime
--!QUANTITY 'TSR', 'CAN_TSSLifeTime'
--$CAN_TSSOverspeedAlert
--!QUANTITY 'TSR', 'CAN_TSSOverspeedAlert'
--$TP
--!QUANTITY 'TSR', 'TP'
--$Total_GT
--!QUANTITY 'TSR', 'Total_GT'
--$FP
--!QUANTITY 'TSR', 'FP'
--$CAN_TP
--!QUANTITY 'TSR', 'CAN_TP'
--$CAN_TN
--!QUANTITY 'TSR', 'CAN_TN'
--$CAN_FP
--!QUANTITY 'TSR', 'CAN_FP'
--$CAN_FP1
--!QUANTITY 'TSR', 'CAN_FP1'
--$CAN_FP2
--!QUANTITY 'TSR', 'CAN_FP2'
--$CAN_FP3
--!QUANTITY 'TSR', 'CAN_FP3'
--$CAN_FN
--!QUANTITY 'TSR', 'CAN_FN'
--$CAN_GT_existance_true
--!QUANTITY 'TSR', 'CAN_GT_existance_true'
--$CAN_GT_existance_false
--!QUANTITY 'TSR', 'CAN_GT_existance_false'
--$CAN_Total_GT
--!QUANTITY 'TSR', 'CAN_Total_GT'
--$FN
--!QUANTITY 'TSR', 'FN'
--$conti_uid
--!QUANTITY 'TSR', 'conti_uid'
--$conti_duration
--!QUANTITY 'TSR', 'conti_duration'
--$can_duration
--!QUANTITY 'TSR', 'can_duration'
--$warning cause
--!LABEL "AEBS event cause"
--$warning rating scale
--!LABEL "event severity"
--$comment
--!COMMENT
