--Query intervals where engine is running / not running

--$fullmeas
--!FULLMEAS
--$measurement
--!MEAS
--$start [s]
--!STARTTIME
--$duration [s]
--!DURATION
--$daytime
--!LABEL "daytime"
--$comment
--!COMMENT
