--Query most important attributes of the FCW event intervals

--$fullmeas
--!FULLMEAS
--$measurement
--!MEAS
--$start [s]
--!STARTTIME
--$duration [s]
--!DURATION
--$moving state
--!LABEL "moving state"
--$asso state
--!LABEL "asso state"
--$cascade phase
--!LABEL "FCW cascade phase"
--$ego speed [km/h]
--!QUANTITY "ego vehicle", "speed start", 3.6
--$dx [m]
--!QUANTITY "target", "dx start"
--$vx [km/h]
--!QUANTITY "target", "vx start", 3.6
--$ax [m/s^2]
--!QUANTITY "target", "ax start"
--$warning rating scale
--!LABEL "event severity"
--$warning cause
--!LABEL "AEBS event cause"
--$comment
--!COMMENT
