--Query most important attributes of the ACC event intervals

--$fullmeas
--!FULLMEAS
--$measurement
--!MEAS
--$start [s]
--!STARTTIME
--$duration [s]
--!DURATION
--$ACC event
--!LABEL "ACC event"
--$dx [m]
--!QUANTITY "ACC check","pedestrian go suppression target present(dx)"
--$comment
--!COMMENT
