"""
:Organization: Knorr-Bremse SfN GmbH T/CES3.2 (BU2) Budapest Schwieberdingen T/CES3.2
:Copyright: 
  Knorr-Bremse SfN GmbH reserves all rights even in the event of industrial 
  property. We reserve all rights of disposal such as copying and passing on to 
  third parties.
"""
import datavis
import measparser
import interface

DefParam = interface.NullParam

SignalGroups = [{"fus.ObjData_TC.FusObj.i0.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i0.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i0.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i0.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i0.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i0.dVarYv"),
                 "fus.ObjData_TC.FusObj.i0.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i0.wExistProb"),
                 "fus.ObjData_TC.FusObj.i0.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i0.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i0.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i0.wObstacle"),
                 "fus.ObjData_TC.FusObj.i1.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i1.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i1.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i1.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i1.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i1.dVarYv"),
                 "fus.ObjData_TC.FusObj.i1.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i1.wExistProb"),
                 "fus.ObjData_TC.FusObj.i1.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i1.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i1.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i1.wObstacle"),
                 "fus.ObjData_TC.FusObj.i10.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i10.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i10.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i10.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i10.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i10.dVarYv"),
                 "fus.ObjData_TC.FusObj.i10.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i10.wExistProb"),
                 "fus.ObjData_TC.FusObj.i10.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i10.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i10.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i10.wObstacle"),
                 "fus.ObjData_TC.FusObj.i11.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i11.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i11.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i11.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i11.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i11.dVarYv"),
                 "fus.ObjData_TC.FusObj.i11.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i11.wExistProb"),
                 "fus.ObjData_TC.FusObj.i11.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i11.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i11.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i11.wObstacle"),
                 "fus.ObjData_TC.FusObj.i12.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i12.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i12.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i12.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i12.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i12.dVarYv"),
                 "fus.ObjData_TC.FusObj.i12.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i12.wExistProb"),
                 "fus.ObjData_TC.FusObj.i12.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i12.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i12.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i12.wObstacle"),
                 "fus.ObjData_TC.FusObj.i13.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i13.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i13.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i13.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i13.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i13.dVarYv"),
                 "fus.ObjData_TC.FusObj.i13.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i13.wExistProb"),
                 "fus.ObjData_TC.FusObj.i13.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i13.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i13.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i13.wObstacle"),
                 "fus.ObjData_TC.FusObj.i14.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i14.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i14.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i14.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i14.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i14.dVarYv"),
                 "fus.ObjData_TC.FusObj.i14.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i14.wExistProb"),
                 "fus.ObjData_TC.FusObj.i14.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i14.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i14.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i14.wObstacle"),
                 "fus.ObjData_TC.FusObj.i15.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i15.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i15.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i15.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i15.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i15.dVarYv"),
                 "fus.ObjData_TC.FusObj.i15.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i15.wExistProb"),
                 "fus.ObjData_TC.FusObj.i15.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i15.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i15.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i15.wObstacle"),
                 "fus.ObjData_TC.FusObj.i16.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i16.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i16.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i16.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i16.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i16.dVarYv"),
                 "fus.ObjData_TC.FusObj.i16.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i16.wExistProb"),
                 "fus.ObjData_TC.FusObj.i16.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i16.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i16.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i16.wObstacle"),
                 "fus.ObjData_TC.FusObj.i17.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i17.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i17.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i17.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i17.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i17.dVarYv"),
                 "fus.ObjData_TC.FusObj.i17.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i17.wExistProb"),
                 "fus.ObjData_TC.FusObj.i17.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i17.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i17.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i17.wObstacle"),
                 "fus.ObjData_TC.FusObj.i18.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i18.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i18.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i18.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i18.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i18.dVarYv"),
                 "fus.ObjData_TC.FusObj.i18.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i18.wExistProb"),
                 "fus.ObjData_TC.FusObj.i18.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i18.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i18.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i18.wObstacle"),
                 "fus.ObjData_TC.FusObj.i19.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i19.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i19.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i19.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i19.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i19.dVarYv"),
                 "fus.ObjData_TC.FusObj.i19.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i19.wExistProb"),
                 "fus.ObjData_TC.FusObj.i19.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i19.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i19.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i19.wObstacle"),
                 "fus.ObjData_TC.FusObj.i2.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i2.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i2.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i2.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i2.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i2.dVarYv"),
                 "fus.ObjData_TC.FusObj.i2.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i2.wExistProb"),
                 "fus.ObjData_TC.FusObj.i2.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i2.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i2.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i2.wObstacle"),
                 "fus.ObjData_TC.FusObj.i20.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i20.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i20.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i20.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i20.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i20.dVarYv"),
                 "fus.ObjData_TC.FusObj.i20.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i20.wExistProb"),
                 "fus.ObjData_TC.FusObj.i20.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i20.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i20.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i20.wObstacle"),
                 "fus.ObjData_TC.FusObj.i21.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i21.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i21.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i21.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i21.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i21.dVarYv"),
                 "fus.ObjData_TC.FusObj.i21.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i21.wExistProb"),
                 "fus.ObjData_TC.FusObj.i21.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i21.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i21.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i21.wObstacle"),
                 "fus.ObjData_TC.FusObj.i22.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i22.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i22.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i22.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i22.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i22.dVarYv"),
                 "fus.ObjData_TC.FusObj.i22.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i22.wExistProb"),
                 "fus.ObjData_TC.FusObj.i22.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i22.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i22.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i22.wObstacle"),
                 "fus.ObjData_TC.FusObj.i23.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i23.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i23.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i23.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i23.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i23.dVarYv"),
                 "fus.ObjData_TC.FusObj.i23.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i23.wExistProb"),
                 "fus.ObjData_TC.FusObj.i23.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i23.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i23.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i23.wObstacle"),
                 "fus.ObjData_TC.FusObj.i24.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i24.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i24.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i24.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i24.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i24.dVarYv"),
                 "fus.ObjData_TC.FusObj.i24.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i24.wExistProb"),
                 "fus.ObjData_TC.FusObj.i24.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i24.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i24.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i24.wObstacle"),
                 "fus.ObjData_TC.FusObj.i25.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i25.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i25.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i25.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i25.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i25.dVarYv"),
                 "fus.ObjData_TC.FusObj.i25.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i25.wExistProb"),
                 "fus.ObjData_TC.FusObj.i25.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i25.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i25.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i25.wObstacle"),
                 "fus.ObjData_TC.FusObj.i26.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i26.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i26.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i26.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i26.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i26.dVarYv"),
                 "fus.ObjData_TC.FusObj.i26.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i26.wExistProb"),
                 "fus.ObjData_TC.FusObj.i26.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i26.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i26.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i26.wObstacle"),
                 "fus.ObjData_TC.FusObj.i27.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i27.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i27.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i27.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i27.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i27.dVarYv"),
                 "fus.ObjData_TC.FusObj.i27.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i27.wExistProb"),
                 "fus.ObjData_TC.FusObj.i27.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i27.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i27.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i27.wObstacle"),
                 "fus.ObjData_TC.FusObj.i28.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i28.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i28.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i28.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i28.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i28.dVarYv"),
                 "fus.ObjData_TC.FusObj.i28.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i28.wExistProb"),
                 "fus.ObjData_TC.FusObj.i28.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i28.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i28.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i28.wObstacle"),
                 "fus.ObjData_TC.FusObj.i29.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i29.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i29.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i29.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i29.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i29.dVarYv"),
                 "fus.ObjData_TC.FusObj.i29.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i29.wExistProb"),
                 "fus.ObjData_TC.FusObj.i29.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i29.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i29.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i29.wObstacle"),
                 "fus.ObjData_TC.FusObj.i3.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i3.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i3.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i3.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i3.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i3.dVarYv"),
                 "fus.ObjData_TC.FusObj.i3.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i3.wExistProb"),
                 "fus.ObjData_TC.FusObj.i3.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i3.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i3.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i3.wObstacle"),
                 "fus.ObjData_TC.FusObj.i30.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i30.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i30.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i30.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i30.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i30.dVarYv"),
                 "fus.ObjData_TC.FusObj.i30.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i30.wExistProb"),
                 "fus.ObjData_TC.FusObj.i30.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i30.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i30.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i30.wObstacle"),
                 "fus.ObjData_TC.FusObj.i31.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i31.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i31.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i31.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i31.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i31.dVarYv"),
                 "fus.ObjData_TC.FusObj.i31.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i31.wExistProb"),
                 "fus.ObjData_TC.FusObj.i31.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i31.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i31.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i31.wObstacle"),
                 "fus.ObjData_TC.FusObj.i32.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i32.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i32.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i32.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i32.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i32.dVarYv"),
                 "fus.ObjData_TC.FusObj.i32.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i32.wExistProb"),
                 "fus.ObjData_TC.FusObj.i32.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i32.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i32.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i32.wObstacle"),
                 "fus.ObjData_TC.FusObj.i4.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i4.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i4.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i4.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i4.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i4.dVarYv"),
                 "fus.ObjData_TC.FusObj.i4.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i4.wExistProb"),
                 "fus.ObjData_TC.FusObj.i4.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i4.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i4.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i4.wObstacle"),
                 "fus.ObjData_TC.FusObj.i5.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i5.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i5.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i5.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i5.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i5.dVarYv"),
                 "fus.ObjData_TC.FusObj.i5.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i5.wExistProb"),
                 "fus.ObjData_TC.FusObj.i5.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i5.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i5.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i5.wObstacle"),
                 "fus.ObjData_TC.FusObj.i6.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i6.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i6.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i6.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i6.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i6.dVarYv"),
                 "fus.ObjData_TC.FusObj.i6.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i6.wExistProb"),
                 "fus.ObjData_TC.FusObj.i6.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i6.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i6.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i6.wObstacle"),
                 "fus.ObjData_TC.FusObj.i7.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i7.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i7.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i7.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i7.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i7.dVarYv"),
                 "fus.ObjData_TC.FusObj.i7.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i7.wExistProb"),
                 "fus.ObjData_TC.FusObj.i7.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i7.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i7.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i7.wObstacle"),
                 "fus.ObjData_TC.FusObj.i8.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i8.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i8.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i8.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i8.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i8.dVarYv"),
                 "fus.ObjData_TC.FusObj.i8.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i8.wExistProb"),
                 "fus.ObjData_TC.FusObj.i8.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i8.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i8.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i8.wObstacle"),
                 "fus.ObjData_TC.FusObj.i9.b.b.NotClassified_b": ("ECU", "fus.ObjData_TC.FusObj.i9.b.b.NotClassified_b"),
                 "fus.ObjData_TC.FusObj.i9.b.b.TruckCabIndicator_b": ("ECU", "fus.ObjData_TC.FusObj.i9.b.b.TruckCabIndicator_b"),
                 "fus.ObjData_TC.FusObj.i9.dVarYv": ("ECU", "fus.ObjData_TC.FusObj.i9.dVarYv"),
                 "fus.ObjData_TC.FusObj.i9.wExistProb": ("ECU", "fus.ObjData_TC.FusObj.i9.wExistProb"),
                 "fus.ObjData_TC.FusObj.i9.wGroundReflex": ("ECU", "fus.ObjData_TC.FusObj.i9.wGroundReflex"),
                 "fus.ObjData_TC.FusObj.i9.wObstacle": ("ECU", "fus.ObjData_TC.FusObj.i9.wObstacle"),
                 "padsit_x_par_a.PCCCFILTwExistProb": ("ECU", "padsit_x_par_a.PCCCFILTwExistProb"),
                 "padsit_x_par_a.PCCCFILTwObstacleProb": ("ECU", "padsit_x_par_a.PCCCFILTwObstacleProb"),
                 "padsit_x_par_a.PCCCFILTdOutOfSight": ("ECU", "padsit_x_par_a.PCCCFILTdOutOfSight"),},]

class cView(interface.iView):
  @classmethod
  def view(Sync, cls, Param=DefParam): 
    try:
      Group = interface.Source.selectSignalGroup(SignalGroups)
    except measparser.signalgroup.SignalGroupError, error:
      print __file__
      print error.message
    else:
      #################################################
      #SIT- acceptance filter - adpat for known object#
      #################################################
      # signals=[] #Erstellen einer leeren Liste
      # for i in xrange(0,33,1):    #0= Beginn der Liste, 41= Ende der Liste, 1= Zaehlschritt
        # signals.append("wExistProb_i%d"%i, "wObstacle_i%d"%i) #Name der Signalbezeichnung
        # signals.append(interface.Source.getSignal('ECU_0_0','fus.ObjData_TC.FusObj.i%d.wExistProb'%i),
                      # interface.Source.getSignal('ECU_0_0','fus.ObjData_TC.FusObj.i%d.wObstacle'%i),
                      # interface.Source.getSignal('ECU_0_0','fus.ObjData_TC.FusObj.i%d.dVarYv'%i),
                      # interface.Source.getSignal('ECU_0_0','fus.ObjData_TC.FusObj.i%d.wGroundReflex'%i),
                      # interface.Source.getSignal('ECU_0_0','fus.ObjData_TC.FusObj.i%d.b.b.TruckCabIndicator_b'%i),
                      # interface.Source.getSignal('ECU_0_0','fus.ObjData_TC.FusObj.i%d.b.b.NotClassified_b'%i)) # Angabe des Geraetes und des Signalnamens
      # Client.addsignal(*signals) #entpacken der liste

      Index=13 #object ID to change for known object
      Client = datavis.cPlotNavigator(title="SIT-acceptance filter, object_i%d"%Index, figureNr=201) 
      interface.Sync.addClient(Client)
      Client.addsignal('wExistProb_i%d []'%Index, interface.Source.getSignalFromSignalGroup(Group, "fus.ObjData_TC.FusObj.i%d.wExistProb"%Index),
                       'wObstacle_i%d []'%Index, interface.Source.getSignalFromSignalGroup(Group, "fus.ObjData_TC.FusObj.i%d.wObstacle"%Index),
                       'wGroundReflex_i%d []'%Index, interface.Source.getSignalFromSignalGroup(Group, "fus.ObjData_TC.FusObj.i%d.wGroundReflex"%Index))
      Client.addsignal('dVarYv_i%d []'%Index, interface.Source.getSignalFromSignalGroup(Group, "fus.ObjData_TC.FusObj.i%d.dVarYv"%Index))
      Client.addsignal('TruckCabIndicator_b_i%d []'%Index, interface.Source.getSignalFromSignalGroup(Group, "fus.ObjData_TC.FusObj.i%d.b.b.TruckCabIndicator_b"%Index),
                       'NotClassified_b_i%d []'%Index, interface.Source.getSignalFromSignalGroup(Group, "fus.ObjData_TC.FusObj.i%d.b.b.NotClassified_b"%Index))
                       
      Client = datavis.cListNavigator(title="SIT-acceptance filter parameter")
      interface.Sync.addClient(Client) 
      Client.addsignal('wExist []', interface.Source.getSignalFromSignalGroup(Group, "padsit_x_par_a.PCCCFILTwExistProb"))
      Client.addsignal('wObstacle []', interface.Source.getSignalFromSignalGroup(Group, "padsit_x_par_a.PCCCFILTwObstacleProb"))
      Client.addsignal('dOutOfSight [m]', interface.Source.getSignalFromSignalGroup(Group, "padsit_x_par_a.PCCCFILTdOutOfSight"))
      return []

