--Query most important attributes of the ACC event intervals

--$fullmeas
--!FULLMEAS
--$measurement
--!MEAS
--$start [s]
--!STARTTIME
--$duration [s]
--!DURATION
--$ACC event
--!LABEL "ACC event"
--$ego speed [km/h]
--!QUANTITY "ego vehicle", "speed start", 3.6
--$dx [m]
--!QUANTITY "target", "dx start"
--$vx [km/h]
--!QUANTITY "target", "vx start", 3.6
--$ax [m/s^2]
--!QUANTITY "target", "ax start"
--$comment
--!COMMENT
