--Query most important attributes of the ACC hogh speed cut-in event intervals

--$fullmeas
--!FULLMEAS
--$measurement
--!MEAS
--$start [s]
--!STARTTIME
--$duration [s]
--!DURATION
--$ACC event
--!LABEL "ACC event"
--$obj dx [m]
--!QUANTITY "ACC check", "acc target present(dx)"
--$xbr
--!QUANTITY "ACC check", "brake request"
--$comment
--!COMMENT
