"""
:Organization: Knorr-Bremse SfN GmbH T/DE Budapest Schwieberdingen T/HEE2
:Copyright: 
  Knorr-Bremse SfN GmbH reserves all rights even in the event of industrial 
  property. We reserve all rights of disposal such as copying and passing on to 
  third parties.

Type definitions for groups
"""

__docformat__ = "restructuredtext en"

OHL_GUARDRAILS = set(['OHL_GUARDRAIL_%d' %i for i in xrange(40)])
FUS_GUARDRAILS = set(['FUS_GUARDRAIL_%d' %i for i in xrange(33)])

AC100_MOV = {'AC100_MOV'}
AC100_STAT = {'AC100_STAT'}
AC100 = AC100_MOV.union(AC100_STAT)

AC100_POS = {'AC100_ACC', 'AC100_IIV', 'AC100_NIV_L', 'AC100_NIV_R','NONE_TYPE'}

AC100_W = {'AC100_CW', 'AC100_CO', 'NONE_TYPE'}

AC100_TARGET_FLAG = {
  'AC100_STAT_TARGET', 'AC100_AMBIGUOUS', 'AC100_WEAK_DET',
  'AC100_WEAK_PARTNER', 'AC100_PHI_ERROR', 'NONE_TYPE',
}

AC100_TARGET_STATUS = {
  'AC100_UNCONF', 'AC100_PARTIAL', 'AC100_SHADED', 'AC100_CONF', 'NONE_TYPE',
}

AC100_TRACKING_FLAG = {
  'AC100_POSITION', 'AC100_CLOSE_TO_ACC', 'AC100_BEHIND_CBR',
  'AC100_CLOSE_LOWPWR', 'AC100_FREQ', 'AC100_CLOSE_TO_TRACK', 'AC100_TYRE',
  'AC100_SEC_PHI_ERR', 'NONE_TYPE',
}

FLR20_MOV = {'FLR20_MOV'}
FLR20_STAT = {'FLR20_STAT'}
FLR20 = FLR20_MOV.union(FLR20_STAT).union( {'NONE_TYPE'} )

FLR20_AEB = {'FLR20_AEB', 'NONE_TYPE'}

FLR20_ACC = {'FLR20_ACC', 'NONE_TYPE'}

FLR20_TARGET = {'FLR20_TARGET', 'NONE_TYPE'}

FLR20_FUSED_MOV = {'FLR20_FUSED_MOV'}
FLR20_FUSED_STAT = {'FLR20_FUSED_STAT'}
FLR20_RADAR_ONLY_MOV = {'FLR20_RADAR_ONLY_MOV'}
FLR20_RADAR_ONLY_STAT = {'FLR20_RADAR_ONLY_STAT'}
# fusion
FLR20_FUSED = FLR20_FUSED_STAT.union(FLR20_FUSED_MOV)
FLR20_RADAR_ONLY = FLR20_RADAR_ONLY_STAT.union(FLR20_RADAR_ONLY_MOV)
# moving state
FLR20_FUS_MOV = FLR20_FUSED_MOV.union(FLR20_RADAR_ONLY_MOV)
FLR20_FUS_STAT = FLR20_FUSED_STAT.union(FLR20_RADAR_ONLY_STAT)
# all
FLR20_FUS = FLR20_FUSED_MOV.union(FLR20_FUSED_STAT).union(FLR20_RADAR_ONLY_MOV)
FLR20_FUS = FLR20_FUS.union(FLR20_RADAR_ONLY_STAT).union( {'NONE_TYPE'} )

FLR20_AEBS_WARNING_KB = {'NONE_TYPE', 'FLR20_AEBS_WARNING_KB'}
FLR20_AEBS_WARNING_TRW = {'NONE_TYPE', 'FLR20_AEBS_WARNING_TRW'}
FLR20_AEBS_WARNING_FLR20 = {'NONE_TYPE', 'FLR20_AEBS_WARNING_FLR20'}
FLR20_AEBS_WARNING_AUTOBOX = {'NONE_TYPE', 'FLR20_AEBS_WARNING_AUTOBOX'}
FLR20_AEBS_WARNING_SIL = {'NONE_TYPE', 'FLR20_AEBS_WARNING_SIL'}

FLR25_MOV = {'FLR25_MOV'}
FLR25_STOPPED ={'FLR25_STOPPED'}
FLR25_STAT = {'FLR25_STAT'}
FLR25 = FLR25_MOV.union(FLR25_STAT, FLR25_STOPPED).union( {'NONE_TYPE'} )

FLR25_AEB = {'FLR25_AEB', 'NONE_TYPE'}
FLC25_AEBS_FIRST_OBJ = {'FLC25_AEBS_FIRST_OBJ', 'NONE_TYPE'}
FLC25_AEBS_SECOND_OBJ = {'FLC25_AEBS_SECOND_OBJ', 'NONE_TYPE'}
FLC25_AEBS_THIRD_OBJ = {'FLC25_AEBS_THIRD_OBJ', 'NONE_TYPE'}
FLC25_MLAEB_LEFT_FIRST_OBJ = {'FLC25_MLAEB_LEFT_FIRST_OBJ', 'NONE_TYPE'}
FLC25_MLAEB_LEFT_SECOND_OBJ = {'FLC25_MLAEB_LEFT_SECOND_OBJ', 'NONE_TYPE'}
FLC25_MLAEB_LEFT_THIRD_OBJ = {'FLC25_MLAEB_LEFT_THIRD_OBJ', 'NONE_TYPE'}
FLC25_MLAEB_RIGHT_FIRST_OBJ = {'FLC25_MLAEB_RIGHT_FIRST_OBJ', 'NONE_TYPE'}
FLC25_MLAEB_RIGHT_SECOND_OBJ = {'FLC25_MLAEB_RIGHT_SECOND_OBJ', 'NONE_TYPE'}
FLC25_MLAEB_RIGHT_THIRD_OBJ = {'FLC25_MLAEB_RIGHT_THIRD_OBJ', 'NONE_TYPE'}
FLR25_AEB_RESIM = {'FLR25_AEB_RESIM', 'NONE_TYPE'}
FLR25_AEB_RETEST_RESIM = {'FLR25_AEB_RETEST_RESIM', 'NONE_TYPE'}
FLR25_AEB_BASELINE_RESIM = {'FLR25_AEB_BASELINE_RESIM', 'NONE_TYPE'}

FLR25_ACC_PED = {'FLR25_ACC_PED', 'NONE_TYPE'}
FLR25_ACC_PED_STOP = {'FLR25_ACC_PED_STOP', 'NONE_TYPE'}

FLR25_ACC_MOV = {'FLR25_ACC_MOV'}
FLR25_ACC_STAT = {'FLR25_ACC_STAT'}
FLR25_ACC_STOPPED ={'FLR25_ACC_STOPPED'}
FLR25_ACC= FLR25_ACC_MOV.union(FLR25_ACC_STAT, FLR25_ACC_STOPPED).union( {'NONE_TYPE'} )

FLR25_ACC_GO_SUPP_PED_MOV = {'FLR25_ACC_GO_SUPP_PED_MOV'}
FLR25_ACC_GO_SUPP_PED_STAT = {'FLR25_ACC_GO_SUPP_PED_STAT'}
FLR25_ACC_GO_SUPP_PED_STOPPED ={'FLR25_ACC_GO_SUPP_PED_STOPPED'}
FLR25_ACC_GO_SUPP_PED= FLR25_ACC_GO_SUPP_PED_MOV.union(FLR25_ACC_GO_SUPP_PED_STAT, FLR25_ACC_GO_SUPP_PED_STOPPED).union( {'NONE_TYPE'} )

SCAM_MOV = {'SCAM_MOV'}
SCAM_STAT = {'SCAM_STAT'}
SCAM = SCAM_MOV.union(SCAM_STAT)

FLC20_MOV = {'FLC20_MOV'}
FLC20_STAT = {'FLC20_STAT'}
FLC20 = FLC20_MOV.union(FLC20_STAT)

FLC25_TSR_STAT = {'FLC25_TSR_STAT'}
FLC25_TSR = FLC25_TSR_STAT.union( {'NONE_TYPE'} )

FLC25_TSR_STAT = {'FLC25_TSR_SHORTLISTED_STAT'}
FLC25_TSR_SHORTLISTED = FLC25_TSR_STAT.union( {'NONE_TYPE'} )

FLC25_CEM_TPF_MOV = {'FLC25_CEM_TPF_MOV'}
FLC25_CEM_TPF_STAT = {'FLC25_CEM_TPF_STAT'}
FLC25_CEM_TPF = FLC25_CEM_TPF_MOV.union(FLC25_CEM_TPF_STAT)

FLC25_CEM_TPF_MG_AOA_ACC_MOV = {'FLC25_CEM_TPF_MG_AOA_ACC_MOV'}
FLC25_CEM_TPF_MG_AOA_ACC_STAT = {'FLC25_CEM_TPF_MG_AOA_ACC_STAT'}
FLC25_CEM_TPF_MG_AOA_ACC = FLC25_CEM_TPF_MG_AOA_ACC_MOV.union(FLC25_CEM_TPF_MG_AOA_ACC_STAT)

FLC25_CAN_MOV = {'FLC25_CAN_MOV'}
FLC25_CAN_STAT = {'FLC25_CAN_STAT'}
FLC25_CAN = FLC25_CAN_MOV.union(FLC25_CAN_STAT)

FLC25_ARS_FCU_MOV = {'FLC25_ARS_FCU_MOV'}
FLC25_ARS_FCU_STAT = {'FLC25_ARS_FCU_STAT'}
FLC25_ARS_FCU= FLC25_ARS_FCU_MOV.union(FLC25_ARS_FCU_STAT)

FLC25_ARS620_MOV = {'FLC25_ARS620_MOV'}
FLC25_ARS620_STAT = {'FLC25_ARS620_STAT'}
FLC25_ARS620= FLC25_ARS620_MOV.union(FLC25_ARS620_STAT)

FLC25_EM_MOV = {'FLC25_EM_MOV'}
FLC25_EM_STAT = {'FLC25_EM_STAT'}
FLC25_EM = FLC25_EM_MOV.union(FLC25_EM_STAT)


FLC25_PAEBS_AOAOUTPUT_MOV = {'FLC25_PAEBS_AOAOUTPUT_MOV'}
FLC25_PAEBS_AOAOUTPUT_STAT = {'FLC25_PAEBS_AOAOUTPUT_STAT'}
FLC25_PAEBS_AOAOUTPUT = FLC25_PAEBS_AOAOUTPUT_MOV.union(FLC25_PAEBS_AOAOUTPUT_STAT)

FLC25_PAEBS_AOAOUTPUT_MOV_RESIM = {'FLC25_PAEBS_AOAOUTPUT_MOV_RESIM'}
FLC25_PAEBS_AOAOUTPUT_STAT_RESIM = {'FLC25_PAEBS_AOAOUTPUT_STAT_RESIM'}
FLC25_PAEBS_AOAOUTPUT_RESIM = FLC25_PAEBS_AOAOUTPUT_MOV_RESIM.union(FLC25_PAEBS_AOAOUTPUT_STAT_RESIM)

FLC25_PAEBS_DEBUG_PED_CROSS = {'FLC25_PAEBS_DEBUG_PED_CROSS'}
FLC25_PAEBS_DEBUG_PED_NOT_CROSS = {'FLC25_PAEBS_DEBUG_PED_NOT_CROSS'}
FLC25_PAEBS_DEBUG_BIC_CROSS = {'FLC25_PAEBS_DEBUG_BIC_CROSS'}
FLC25_PAEBS_DEBUG_BIC_NOT_CROSS = {'FLC25_PAEBS_DEBUG_BIC_NOT_CROSS'}
FLC25_PAEBS_DEBUG_UNDEFINED = {'FLC25_PAEBS_DEBUG_UNDEFINED'}
FLC25_PAEBS_DEBUG = FLC25_PAEBS_DEBUG_PED_CROSS.union(FLC25_PAEBS_DEBUG_PED_CROSS,FLC25_PAEBS_DEBUG_PED_NOT_CROSS,FLC25_PAEBS_DEBUG_BIC_CROSS,FLC25_PAEBS_DEBUG_BIC_NOT_CROSS,FLC25_PAEBS_DEBUG_UNDEFINED)

FLC25_PAEBS_LAUSCH_PED_CROSS = {'FLC25_PAEBS_LAUSCH_PED_CROSS'}
FLC25_PAEBS_LAUSCH_PED_NOT_CROSS = {'FLC25_PAEBS_LAUSCH_PED_NOT_CROSS'}
FLC25_PAEBS_LAUSCH_UNDEFINED = {'FLC25_PAEBS_LAUSCH_UNDEFINED'}
FLC25_PAEBS_LAUSCH = FLC25_PAEBS_DEBUG_PED_CROSS.union(FLC25_PAEBS_LAUSCH_PED_CROSS,FLC25_PAEBS_LAUSCH_PED_NOT_CROSS,FLC25_PAEBS_LAUSCH_UNDEFINED)

FLC25_PAEBS_CAN_MOV = {'FLC25_PAEBS_CAN_MOV'}
FLC25_PAEBS_CAN_STAT = {'FLC25_PAEBS_CAN_STAT'}
FLC25_PAEBS_CAN = FLC25_PAEBS_CAN_MOV.union(FLC25_PAEBS_CAN_STAT)

FLC25_AOA_AEBS_MOV = {'FLC25_AOA_AEBS_MOV'}
FLC25_AOA_AEBS_STAT = {'FLC25_AOA_AEBS_STAT'}
FLC25_AOA_AEBS = FLC25_AOA_AEBS_MOV.union(FLC25_AOA_AEBS_STAT)

FLC25_AOA_ACC_MOV = {'FLC25_AOA_ACC_MOV'}
FLC25_AOA_ACC_STAT = {'FLC25_AOA_ACC_STAT'}
FLC25_AOA_ACC = FLC25_AOA_ACC_MOV.union(FLC25_AOA_ACC_STAT)

GT_FREEBOARD_STAT = {'GT_FREEBOARD_STAT'}
GT_FREEBOARD= GT_FREEBOARD_STAT.union( {'NONE_TYPE'})

GT_DELTA_STAT = {'GT_DELTA_STAT'}
GT_DELTA = GT_DELTA_STAT.union( {'NONE_TYPE'})

SLR25_RFB_MOV = {'SLR25_RFB_MOV'}
SLR25_RFB_STAT = {'SLR25_RFB_STAT'}
SLR25_RFB = SLR25_RFB_MOV.union(SLR25_RFB_STAT)

SLR25_RFF_MOV = {'SLR25_RFF_MOV'}
SLR25_RFF_STAT = {'SLR25_RFF_STAT'}
SLR25_RFF = SLR25_RFF_MOV.union(SLR25_RFF_STAT)

SLR25_Front_MOV = {'SLR25_Front_MOV'}
SLR25_Front_STAT = {'SLR25_Front_STAT'}
SLR25_Front = SLR25_Front_MOV.union(SLR25_Front_STAT)

ESR_MOV = {'ESR_MOV'}
ESR_STAT = {'ESR_STAT'}
ESR = ESR_MOV.union(ESR_STAT)

IBEO_MOV = {'IBEO_MOV'}
IBEO_STAT = {'IBEO_STAT'}
IBEO = IBEO_MOV.union(IBEO_STAT)

VFP_MOV = {'VFP_MOV'}
VFP_STAT = {'VFP_STAT'}
VFP = {'VFP_PEDESTRIAN'}
VFP.update(VFP_MOV)
VFP.update(VFP_STAT)

SDF_LRR3_CVR3_OHL = {'SDF_LRR3_CVR3_OHL', 'NONE_TYPE'}
SDF_CVR3_SCAM_CIPV = {'SDF_CVR3_SCAM_CIPV', 'NONE_TYPE'}

SDF_CVR3_SCAM_MOV = {'SDF_CVR3_SCAM_MOV'}
SDF_CVR3_SCAM_STAT = {'SDF_CVR3_SCAM_STAT'}
SDF_CVR3_SCAM = {'NONE_TYPE'}
SDF_CVR3_SCAM.update(SDF_CVR3_SCAM_MOV)
SDF_CVR3_SCAM.update(SDF_CVR3_SCAM_STAT)

CVR3_FUS_VID = {'CVR3_FUS_VID', 'NONE_TYPE'}

CVR3_ATS_MOV = {'CVR3_ATS_MOV'}
CVR3_ATS_STAT = {'CVR3_ATS_STAT'}
CVR3_ATS = CVR3_ATS_MOV.union(CVR3_ATS_STAT)


LRR3_ATS_MOV = {'LRR3_ATS_MOV'}
LRR3_ATS_STAT = {'LRR3_ATS_STAT'}
LRR3_ATS = LRR3_ATS_MOV.union(LRR3_ATS_STAT)

CVR3_FUS_FUSED_MOV = {'CVR3_FUS_FUSED_MOV'}
CVR3_FUS_FUSED_STAT = {'CVR3_FUS_FUSED_STAT'}
CVR3_FUS_FUSED = CVR3_FUS_FUSED_MOV.union(CVR3_FUS_FUSED_STAT)

CVR3_FUS_RADAR_ONLY_MOV = {'CVR3_FUS_RADAR_ONLY_MOV'}
CVR3_FUS_RADAR_ONLY_STAT = {'CVR3_FUS_RADAR_ONLY_STAT'}
CVR3_FUS_RADAR_ONLY = CVR3_FUS_RADAR_ONLY_MOV.union(CVR3_FUS_RADAR_ONLY_STAT)

CVR3_FUS_VIDEO_ONLY_MOV = {'CVR3_FUS_VIDEO_ONLY_MOV'}
CVR3_FUS_VIDEO_ONLY_STAT = {'CVR3_FUS_VIDEO_ONLY_STAT'}
CVR3_FUS_VIDEO_ONLY = CVR3_FUS_VIDEO_ONLY_MOV.union(CVR3_FUS_VIDEO_ONLY_STAT)

LRR3_FUS_MOV = {'LRR3_FUS_MOV'}
LRR3_FUS_STAT = {'LRR3_FUS_STAT'}
LRR3_FUS  = {'NONE_TYPE'}
LRR3_FUS.update(LRR3_FUS_MOV)
LRR3_FUS.update(LRR3_FUS_STAT)

CVR3_LOC_INVALID = {'CVR3_LOC_INVALID'}
CVR3_LOC_VALID = {'CVR3_LOC_VALID'}
CVR3_LOC = CVR3_LOC_INVALID.union(CVR3_LOC_VALID) 

LRR3_LOC_INVALID = {'LRR3_LOC_INVALID'}
LRR3_LOC_VALID = {'LRR3_LOC_VALID'}
LRR3_LOC = LRR3_LOC_INVALID.union(LRR3_LOC_VALID) 

CVR3_OHL_MOV  = {'CVR3_OHL_MOV'}
CVR3_OHL_STAT  = {'CVR3_OHL_STAT'}
CVR3_OHL  = CVR3_OHL_MOV.union(CVR3_OHL_STAT)

LRR3_OHL_MOV = {'LRR3_OHL_MOV'}
LRR3_OHL_STAT = {'LRR3_OHL_STAT'}
LRR3_OHL = LRR3_OHL_MOV.union(LRR3_OHL_STAT)

CVR3_POS_MOV = {'CVR3_POS_MOV'}
CVR3_POS_STAT = {'CVR3_POS_STAT'}
CVR3_POS = {'CVR3_POS_INTRO', 'CVR3_ASF_WARNING', 'NONE_TYPE'}
CVR3_POS.update(CVR3_POS_MOV)
CVR3_POS.update(CVR3_POS_STAT)

LRR3_POS_MOV = {'LRR3_POS_MOV'}
LRR3_POS_STAT = {'LRR3_POS_STAT'}
LRR3_POS = LRR3_POS_MOV.union(LRR3_POS_STAT)

CVR3_SIT_MOV = {'CVR3_SIT_MOV'}
CVR3_SIT_STAT = {'CVR3_SIT_STAT'}
CVR3_SIT = CVR3_SIT_MOV.union(CVR3_SIT_STAT)


LRR3_SIT_MOV = {'LRR3_SIT_MOV'}
LRR3_SIT_STAT = {'LRR3_SIT_STAT'}
LRR3_SIT = LRR3_SIT_MOV.union(LRR3_SIT_STAT)

LRR3_ASF  = {
  'LRR3_ASF_BRAKE', 'LRR3_ASF_WARNING', 'LRR3_ASF_VIDEOCONF', 'NONE_TYPE',
}

MBL2_TARGET = {'MBL2_TARGET', 'NONE_TYPE'}

MBL2_TRACK = {'MBL2_TRACK', 'NONE_TYPE'}

MB79_TARGET = {'MB79_TARGET', 'NONE_TYPE'}

KB_TARGET = {'KB_TARGET', 'NONE_TYPE'}

MB79_DET_REPR = {'MB79_DET_REPR', 'NONE_TYPE'}

MB79_TRACK_MOV = {'MB79_TRACK_MOV', 'NONE_TYPE'}
MB79_TRACK_STAT = {'MB79_TRACK_STAT', 'NONE_TYPE'}
MB79_TRACK = MB79_TRACK_STAT.union(MB79_TRACK_MOV)

KB_TRACK_MOV = {'KB_TRACK_MOV', 'NONE_TYPE'}
KB_TRACK_STAT = {'KB_TRACK_STAT', 'NONE_TYPE'}
KB_TRACK_STOP = {'KB_TRACK_STOP', 'NONE_TYPE'}
KB_TRACK_UNK = {'KB_TRACK_UNK', 'NONE_TYPE'}
KB_TRACK = KB_TRACK_STAT.union(KB_TRACK_MOV, KB_TRACK_STOP, KB_TRACK_UNK)

KB_INFO_AREA = {'KB_INFO_AREA', 'NONE_TYPE'}
KB_HAZARD_AREA = {'KB_HAZARD_AREA', 'NONE_TYPE'}

KB_CLUSTERS = {'KB_CLUSTERS', 'NONE_TYPE'}

MB79_KB_WARNING_TRACK = {'MB79_KB_WARNING_TRACK', 'NONE_TYPE'}

FURUKAWA_TARGETS = {'FURUKAWA_TARGET', 'NONE_TYPE'}

CONTI_ARS430_MOVING ={'CONTI_ARS430_MOVING', 'NONE_TYPE'}
CONTI_ARS430_STOPPED ={'CONTI_ARS430_STOPPED', 'NONE_TYPE'}
CONTI_ARS430_STAT ={'CONTI_ARS430_STAT', 'NONE_TYPE'}
CONTI_ARS430 = CONTI_ARS430_MOVING.union(CONTI_ARS430_STOPPED, CONTI_ARS430_STAT)

CONTI_SRR320 ={'CONTI_SRR320', 'NONE_TYPE'}

CONTI_AEBS_WARNING = {'CONTI_AEBS_WARNING', 'NONE_TYPE'}

CONTI_ARS440_MOVING ={'CONTI_ARS440_MOVING', 'NONE_TYPE'}
CONTI_ARS440_STOPPED ={'CONTI_ARS440_STOPPED', 'NONE_TYPE'}
CONTI_ARS440_STAT ={'CONTI_ARS440_STAT', 'NONE_TYPE'}
CONTI_ARS440 = CONTI_ARS440_MOVING.union(CONTI_ARS440_STOPPED, CONTI_ARS440_STAT)

ITERIS = {'ITERIS'}

MOBILEYE = {'MOBILEYE'}

VBOX_OBJ = {'VBOX_OBJ', 'NONE_TYPE'}

NOT_GUARDRAIL = {'NOT_GUARDRAIL'}

NONES = {'UNKNOWN_OBJECT', 'NONE_TYPE'}
ORPHANS = {'INTROS', 'SDF_CVR3_AC100'}

GroupTypes = set()
for Name, Value in globals().items():
  if Name == 'GroupTypes' or not isinstance(Value, set): continue
  GroupTypes.update(Value)

if __name__ == '__main__':
  print OHL_GUARDRAILS
  print FUS_GUARDRAILS
