--TBD

--$fullmeas
--!FULLMEAS
--$measurement
--!MEAS
--$start [s]
--!STARTTIME
--$duration [s]
--!DURATION
--$FLC25 event
--!LABEL "FLC25 events"
--$SwitchOver From
--!LABEL "FLC25 CEM TPF Old ID"
--$SwitchOver To
--!LABEL "FLC25 CEM TPF New ID"
--$Previous Track End(vx)
--!QUANTITY "FLC25 Object SwitchOver check", "Old Track End(vx)"
--$Previous Track End(vx_abs)
--!QUANTITY "FLC25 Object SwitchOver check", "Old Track End(vx_abs)"
--$Previous Track End(dx)
--!QUANTITY "FLC25 Object SwitchOver check", "Old Track End(dx)"
--$Previous Track End(dy)
--!QUANTITY "FLC25 Object SwitchOver check", "Old Track End(dy)"
--$New Track St(vx)
--!QUANTITY "FLC25 Object SwitchOver check", "New Track St(vx)"
--$New Track St(vx_abs)
--!QUANTITY "FLC25 Object SwitchOver check", "New Track St(vx_abs)"
--$New Track St(dx)
--!QUANTITY "FLC25 Object SwitchOver check", "New Track St(dx)"
--$New Track St(dy)
--!QUANTITY "FLC25 Object SwitchOver check", "New Track St(dy)"
--$comment
--!COMMENT
