--TBD

--$fullmeas
--!FULLMEAS
--$measurement
--!MEAS
--$start [s]
--!STARTTIME
--$duration [s]
--!DURATION
--$FLC25 event
--!LABEL "FLC25 events"
--$Object ID
--!QUANTITY "FLC25 check", "obj_id"
--$Delta DistanceX
--!QUANTITY "FLC25 check", "obj_distx_jump"
--$Object DistanceX
--!QUANTITY "FLC25 check", "obj_distx_val"
--$Delta DistanceY
--!QUANTITY "FLC25 check", "obj_disty_jump"
--$Object DistanceY
--!QUANTITY "FLC25 check", "obj_disty_val"
--$comment
--!COMMENT
